blueprint:
  name: Tlačítko ovládá zařízení (toggle)
  description: Po stisknutí tlačítka se přepne stav vybrané entity (zapne/vypne).
  domain: automation
  input:
    button:
      name: Tlačítko
      description: Entita tlačítka (např. Tasmota switch nebo GPIO)
      selector:
        entity:
          domain: switch
    target:
      name: Ovládaná entita
      description: Entita, kterou má tlačítko ovládat (light, switch apod.)
      selector:
        entity:

trigger:
  - platform: state
    entity_id: !input button
    to: "on"

action:
  - service: homeassistant.toggle
    target:
      entity_id: !input target

mode: single
