blueprint:
  name: Nezávislá synchronizace A a B
  description: |
    Synchronizuje změny stavů uvnitř skupiny A a skupiny B, ale skupiny mezi sebou nejsou propojené.
    Můžeš zadat jen A, jen B, nebo oboje.
  domain: automation
  homeassistant:
    min_version: 2022.5.0

  input:
    group_a:
      name: Skupina A (např. světla)
      selector:
        entity:
          multiple: true
          optional: true
    group_b:
      name: Skupina B (např. spínače)
      selector:
        entity:
          multiple: true
          optional: true

variables:
  group_a: !input group_a
  group_b: !input group_b

trigger:
  - platform: state
    entity_id: !input group_a
  - platform: state
    entity_id: !input group_b

mode: queued
max_exceeded: silent

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  - condition: template
    value_template: >
      {{ (as_timestamp(trigger.to_state.last_changed) - as_timestamp(trigger.from_state.last_changed)) > 0.1 }}

action:
  - variables:
      source_entity: "{{ trigger.entity_id }}"
      source_group: >-
        {% if source_entity in group_a %}
          a
        {% elif source_entity in group_b %}
          b
        {% else %}
          none
        {% endif %}
  - choose:
      - conditions: "{{ source_group == 'a' }}"
        sequence:
          - service: homeassistant.turn_{{ trigger.to_state.state }}
            target:
              entity_id: >
                {% set others = expand(group_a) | rejectattr('entity_id', 'equalto', source_entity) | map(attribute='entity_id') | list %}
                {{ others }}
      - conditions: "{{ source_group == 'b' }}"
        sequence:
          - service: homeassistant.turn_{{ trigger.to_state.state }}
            target:
              entity_id: >
                {% set others = expand(group_b) | rejectattr('entity_id', 'equalto', source_entity) | map(attribute='entity_id') | list %}
                {{ others }}
