blueprint:
  name: Dvě tlačítka ovládají dvě zařízení
  description: Každé tlačítko přepíná (toggle) vlastní cílovou entitu.
  domain: automation
  input:
    button_1:
      name: Tlačítko 1
      selector:
        entity:
          domain: switch
    target_1:
      name: Zařízení 1 (co ovládá tlačítko 1)
      selector:
        entity:
    button_2:
      name: Tlačítko 2
      selector:
        entity:
          domain: switch
    target_2:
      name: Zařízení 2 (co ovládá tlačítko 2)
      selector:
        entity:

trigger:
  - platform: state
    entity_id: !input button_1
    to: "on"
    id: b1
  - platform: state
    entity_id: !input button_2
    to: "on"
    id: b2

action:
  - choose:
      - conditions:
          - condition: trigger
            id: b1
        sequence:
          - service: homeassistant.toggle
            target:
              entity_id: !input target_1
      - conditions:
          - condition: trigger
            id: b2
        sequence:
          - service: homeassistant.toggle
            target:
              entity_id: !input target_2

mode: single
