blueprint:
  name: Link Multiple Switches and Lights (upravený)
  description: |
    ## Link multiple switches and lights together v1.1.0 (upravený)
    Select multiple switch and light entities to link their on/off state.
    If any selected switch or light entity is turned on or off, the other selected entities will be sent a matching on or off command.
    Requires Home Assistant 2022.5.0 or newer.
    Upraveno pro lepší kompatibilitu s Tasmota tlačítky.
  domain: automation
  homeassistant:
    min_version: 2022.5.0
  input:
    lights:
      name: Light Entities
      selector:
        entity:
          domain:
            - light
          multiple: true
    switches:
      name: Switch Entities
      selector:
        entity:
          domain:
            - switch
          multiple: true
    sync_lights:
      name: Sync Lights (Light to Light)
      default: false
      selector:
        boolean:
variables:
  switches: !input switches
  lights: !input lights
  sync_lights: !input sync_lights

trigger:
  - platform: state
    entity_id: !input switches
  - platform: state
    entity_id: !input lights

mode: queued
max_exceeded: silent

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  # odstranena podminka na context, pridana kontrola na rozdil casu zmeny
  - condition: template
    value_template: >
      {{ (as_timestamp(trigger.to_state.last_changed) - as_timestamp(trigger.from_state.last_changed)) > 0.1 }}

action:
  - service: switch.turn_{{ trigger.to_state.state }}
    target:
      entity_id: >
        {{ expand(switches) 
           | selectattr('entity_id', '!=', trigger.entity_id) 
           | map(attribute='entity_id') 
           | list }}
  - service: light.turn_{{ trigger.to_state.state }}
    target:
      entity_id: >
        {% if trigger.entity_id.split('.')[0] == 'switch' or sync_lights %}
          {{ expand(lights) 
             | selectattr('entity_id', '!=', trigger.entity_id) 
             | map(attribute='entity_id') 
             | list }}
        {% else %}
          [] 
        {% endif %}
