blueprint:
  name: Kurva 4x Flexibilní Synchronizace
  description: >
    Propojí 4 páry entit. Každý pár má dvě entity, které se synchronizují.
    Můžeš vybrat entitu z nabídky (switch, light, input_boolean), nebo zadat entity_id ručně jako text.
    Přepíná se přes homeassistant.turn_on/off, takže to funguje na většinu typů.
  domain: automation
  input:

    entity1a:
      name: Entita 1A
      description: Vyber nebo zadej entity_id
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean
    entity1b:
      name: Entita 1B
      description: Vyber nebo zadej entity_id
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean

    entity2a:
      name: Entita 2A
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean
    entity2b:
      name: Entita 2B
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean

    entity3a:
      name: Entita 3A
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean
    entity3b:
      name: Entita 3B
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean

    entity4a:
      name: Entita 4A
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean
    entity4b:
      name: Entita 4B
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
            - domain: input_boolean

trigger:
  - platform: state
    entity_id: !input entity1a
  - platform: state
    entity_id: !input entity1b
  - platform: state
    entity_id: !input entity2a
  - platform: state
    entity_id: !input entity2b
  - platform: state
    entity_id: !input entity3a
  - platform: state
    entity_id: !input entity3b
  - platform: state
    entity_id: !input entity4a
  - platform: state
    entity_id: !input entity4b

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity1a) and trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input entity1b
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity1b) and trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input entity1a

      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity2a) and trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input entity2b
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity2b) and trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input entity2a

      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity3a) and trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input entity3b
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity3b) and trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input entity3a

      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity4a) and trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input entity4b
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (entity4b) and trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input entity4a
mode: restart
