blueprint:
  name: synchronizace
  description: |
    ## HA
  domain: automation
  homeassistant:
    min_version: 2022.5.0
  input:
    lights:
      name: Entities Group A (např. světla)
      selector:
        entity:
          multiple: true
    switches:
      name: Entities Group B (např. spínače)
      selector:
        entity:
          multiple: true

variables:
  switches: !input switches
  lights: !input lights

trigger:
  - platform: state
    entity_id: !input switches
  - platform: state
    entity_id: !input lights

mode: queued
max_exceeded: silent

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  - condition: template
    value_template: >
      {{ (as_timestamp(trigger.to_state.last_changed) - as_timestamp(trigger.from_state.last_changed)) > 0.1 }}

action:
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    target:
      entity_id: >
        {% set all_entities = expand(switches + lights) %}
        {{ all_entities
            | selectattr('entity_id', '!=', trigger.entity_id)
            | map(attribute='entity_id')
            | list }}
